<?php

namespace App\Mail;

use Illuminate\Auth\Notifications\VerifyEmail;

class Mail extends VerifyEmail
{
    protected function buildMailMessage($url)
    {
        return parent::buildMailMessage($url); // TODO: Change the autogenerated stub
    }
}
